version: "2"
linters:
  enable:
    - misspell
    - unconvert
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        text: defer.*Close
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
