version: 2
env:
  - REPO={{ .Env.ACCOUNT }}.dkr.ecr.ca-central-1.amazonaws.com/discordbots
builds:
  - id: copypastabotv2
    binary: copypastabotv2
    dir: ./cmd/copypastabotv2
    ldflags:
      - -s
      - -w
      - -linkmode
      - external
      - -extldflags
      - "-static"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      pre:
        - dir: ./cmd/copypastabotv2
          cmd: go mod tidy
checksum:
  name_template: "checksums.txt"
dockers:
  - id: copypastabotv2-build
    ids:
      - copypastabotv2
    goarch: amd64
    build_flag_templates:
      - "--build-arg=KIND=copypastabotv2"
    image_templates:
      - "{{ .Env.REPO }}:{{ tolower .ProjectName }}-{{ .Version }}"
      - "{{ .Env.REPO }}:{{ tolower .ProjectName }}-latest"
    dockerfile: Dockerfile
docker_manifests:
  - name_template: "{{ .Env.REPO }}:{{ tolower .ProjectName }}-{{ .Version }}"
    image_templates:
      - "{{ .Env.REPO }}:{{ tolower .ProjectName }}-{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
