# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {

    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.24.0"
    }


    hcp = {
      version = "~> 0.76.0"
      source  = "hashicorp/hcp"
    }


    kubernetes = {
      version = "~> 2.23.0"
      source  = "hashicorp/kubernetes"
    }


  }
  required_version = ">= 1.2.2"
}
