# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

provider "kubernetes" {
  config_path = "/home/stollenaar/.kube/config"
}


provider "helm" {
  kubernetes {
    config_path = "/home/stollenaar/.kube/config"
  }
}


